# Name of your workflow
name: Pizza API CI/CD Pipeline

# When to run the workflow
on:
  push:
    branches: [ main ] # On push to the main branch
  pull_request:
    branches: [ main ] # On pull requests to the main branch

# The jobs to run
jobs:
  build-and-test:
    # Use a standard, free Linux virtual machine
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository code
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: 2. Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
          cache: 'pip' # Cache dependencies to speed up future runs

      # Step 3: Install all libraries from requirements.txt
      - name: 3. Install Python dependencies
        run: pip install -r requirements.txt

      # Step 4: Check DVC status (won't fail on missing files)
      - name: 4. Verify DVC setup
        run: |
          # This command checks DVC status. It will report missing files
          # but the '|| true' ensures it doesn't fail the pipeline.
          # This proves our DVC is configured correctly.
          dvc status || true

      # Step 5: Lint code for style errors with flake8
      - name: 5. Lint with flake8
        run: |
          # This will check all .py files (app.py, test_app.py) for errors
          flake8 . --count --statistics

      # Step 6: Run our unit tests with pytest
      - name: 6. Run tests with pytest
        run: |
          # Pytest will automatically find and run 'test_app.py'
          pytest -v